### ISSUE TITLE
Having this mod active prevents game from starting

### ISSUE THREAD

**Issue by Alatarius** [CowboyLva/ebiomes#4]
After activating this mod and trying to start any game with it activated game shuts down and gives me this error:

ModError: Failed to load and run script from D:\Games\Minetest\bin\..\mods\ebiomes\init.lua:
D:\Games\Minetest\bin\..\mods\leads/internal.lua:45: Attempt to override non-existent item stair_wood
stack traceback:
	[C]: in function 'error'
	D:\Games\Minetest\bin\..\builtin\game\register.lua:415: in function 'override_item'
	D:\Games\Minetest\bin\..\mods\leads/internal.lua:45: in function '_after_register_item'
	D:\Games\Minetest\bin\..\mods\leads/internal.lua:65: in function 'register_item'
	D:\Games\Minetest\bin\..\builtin\game\register.lua:225: in function 'really_register_node'
	...test\bin\..\mods\technic_plus\technic_worldgen/nodes.lua:159: in function 'really_register_node'
	...est\bin\..\mods\technic_plus\technic_worldgen/crafts.lua:163: in function 'register_node'
	...es\Minetest\bin\..\mods\moreblocks/stairsplus/common.lua:179: in function 'register_single'
	...es\Minetest\bin\..\mods\moreblocks/stairsplus/stairs.lua:39: in function 'register_stair'
	...ames\Minetest\bin\..\mods\moreblocks/stairsplus/init.lua:40: in function 'register_all'
	D:\Games\Minetest\bin\..\mods\ebiomes/savanna.lua:815: in main chunk
	[C]: in function 'dofile'
	D:\Games\Minetest\bin\..\mods\ebiomes\init.lua:46: in main chunk
Check debug.txt for details.

[edit]
This is on minetest 5.7.0 playing mt_game

**Comment by CowboyLva** [comment]
Tested both minetest 5.8 and 5.7 with current ContentDB versions of:
leads, moreblocks and stairsplus, Technic Plus and Extra Biomes
Didn't encounter this or similar errors, so the issue seems to have resolved on it's own.
