### ISSUE TITLE
breaks tree and plant spawning in ethereal and everness mods

### ISSUE THREAD

**Issue by FloraMaeWolfe** [CowboyLva/ebiomes#6]
breaks tree and plant spawning in ethereal and everness mods

This issue has bugged me for days and finally found out this mod is somehow doing it. Disabling it fixes the issues with plant and tree spawning but i would like to keep this mod.

**Comment by CowboyLva** [comment]
Go to mod settings in settings menu and uncheck "Reregister MTG Decorations"
It's in the readme.
