### ISSUE TITLE
`rereg_mtg_decors` setting should be off by default

### ISSUE THREAD

**Issue by livphi** [CowboyLva/ebiomes#7]
This setting just makes the `ebiomes` mod incompatible with other mods for no reason. Why is it on by default? If someone makes a server and then realized that this setting is causing all the other biome mods to not work, then those loaded mapblocks are now broken. Since biome mod incompatibility can make the world permanantly broken, mod authors should be very cautious. I was only able to find this setting by reading the README for this mod. I'm sorry for assuming that this mod wouldn't do any weird things that cause other biomes to not spawn grass and trees? This is the only biome mod that does this. In my opinion, biome mods should not purposefully be made incompatible with each other. Making it off by default would be the best solution for this problem.
I'm not sure why you would need to reregister Minetest Game decorations? Whats the point and is it worth the huge incompatibility?

**Comment by livphi** [comment]
Here's our fork where I made this setting off by default https://gitlab.com/validandloved/ebiomes

**Comment by CowboyLva** [comment]
1. In the Readme

To remove blackberry from snowy_grassland the default mod together with other vanilla game mods have had their decorations reregistered. So far there is no method(dev term, look up the minetest modding wiki or doc folder in install/build minetest directory(not .minetest)) designed to remove or change a single decoration.

Also once this is implemented I could do away with the reregistration.(At cost of requiring people to use a newer version of the minetest engine)
https://github.com/minetest/minetest/issues/12881
https://github.com/minetest/minetest/pull/14361

2. The mod implements many biomes, other biome mods can break the aesthetic, the toggle is there for those who want to combine biome mods. So I default on the setting being on.

3. "I'm sorry for assuming that this mod wouldn't do any weird things that cause other biomes to not spawn grass and trees? This is the only biome mod that does this."
I may add a more visible warning whilst the problem with the scripting api persists. I may also not do it.

4. "In my opinion, biome mods should not purposefully be made incompatible with each other."
This is incorrect and outright malicious statement, therefore I must bar you and your accomplice from participation.

**Comment by CowboyLva** [comment]
Correction
malicious statement should be malicious allegation
